

spring:
    profiles: product

    datasource:
      url: jdbc:mysql://localhost:3306/hackday_db?useSSL=false&characterEncoding=utf8
      username: hackday_dev
      password: 1234




---
server:
  port: 80

spring:
  profiles: dev


  datasource:
        url: jdbc:mysql://localhost:3306/hackday_db?useSSL=false
        username: hackday_dev
        password: 1234

